Universe   = container
container_image = docker://lsvaren/transformers2
arguments = $(seed)
Executable = run.sh

transfer_input_files = SHG_generation.py, Opacity.py, Rasterize.py, SplineSample.py, SyntheticGen.py, VectorField.py, vf_viz.py

#+WantGPULab = true
+WantFlock = true
Requirements = (Target.HasCHTCStaging == true) && (Machine != "gpu4003.chtc.wisc.edu")
#Requirements = (Machine != "bhaskargpu4000.chtc.wisc.edu")
#gpus_minimum_capability = 7.5
#gpus_minimum_memory = 30 GB
request_memory = 32 GB
request_disk = 12 GB
request_cpus = 3
#request_gpus = 1

batch_name = SHG_$(seed)
output = SHG_$(seed).out
error  = SHG_$(seed).err
log    = SHG_$(seed).log

queue seed from (
    100
    200
    300
    400
    500
    600
    700
    800
    900
    1000
)
